repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: cargo fmt --all --check
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: cargo clippy --all-targets --all-features -- -D warnings
        pass_filenames: false

      - id: cargo-deny
        name: cargo deny
        language: system
        entry: cargo deny check
        pass_filenames: false

      - id: cargo-audit
        name: cargo audit
        language: system
        entry: cargo audit
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        language: system
        entry: cargo test
        pass_filenames: false
        stages: [pre-push]
