repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: make fmt-check
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: make lint
        pass_filenames: false

      - id: cargo-audit
        name: cargo audit
        language: system
        entry: make audit
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        language: system
        entry: make test
        pass_filenames: false
        stages: [pre-push]
